import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Ceavex',
  description: 'Generated by create next app',
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <main className='container'>{children}</main>;
}
