import type { Metadata } from 'next';

import { Header } from '@/components/ui';

export const metadata: Metadata = {
  title: 'Ceavex',
  description: 'Generated by create next app',
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Header />
      <main className='container'>{children}</main>
    </>
  );
}
